=== Petrovich-A/EPAM-Task-Xml-Parsing/src/main/resources/files/computers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema attributeFormDefault="unqualified" elementFormDefault="qualified"
        targetNamespace="http://www.example.com/computers" xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:com="http://www.example.com/computers">

    <element name="abstract-device" abstract="true" type="com:Device"/>
    <element name="cpu" substitutionGroup="com:abstract-device" type="com:Cpu"/>
    <element name="hdd" substitutionGroup="com:abstract-device" type="com:Hdd"/>

    <element name="devices">
        <complexType>
            <sequence>
                <element ref="com:abstract-device"
                         minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Device">
        <sequence>
            <element name="name" type="string"/>
            <element name="delivery-date" type="date"/>
            <element name="country">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Canada"/>
                        <enumeration value="Taiwan"/>
                        <enumeration value="Singapore"/>
                        <enumeration value="USA"/>
                        <enumeration value="Israel"/>
                        <enumeration value="Belarus"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="price">
                <simpleType>
                    <restriction base="double">
                        <minInclusive value="0.0"/>
                        <maxInclusive value="10000.0"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="atribute">
                <complexType>
                    <sequence>
                        <element name="peripheral">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="in case"/>
                                    <enumeration value="output device"/>
                                    <enumeration value="input device"/>
                                </restriction>
                            </simpleType>
                        </element>
                        <element name="port"/>
                    </sequence>
                </complexType>
            </element>
            <element name="critical" type="boolean" default="true"></element>
        </sequence>
        <attribute name="id" use="required" type="com:DeviceID"/>
        <attribute type="string" name="picture" use="optional" default="pic.png"/>
    </complexType>

    <simpleType name="DeviceID">
        <restriction base="ID">
            <pattern value="[A-Z]{2}\d+"></pattern>
        </restriction>
    </simpleType>

    <complexType name="Cpu">
        <complexContent>
            <extension base="com:Device">
                <sequence>
                    <element name="sequanse" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Hdd">
        <complexContent>
            <extension base="com:Device">
                <sequence>
                    <element name="volume" type="double"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== Petrovich-A/EPAM-Task-Xml-Parsing/src/test/resources/files/computers.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/computers"
         xsi:schemaLocation="http://www.example.com/computers computers.xsd">

    <cpu id="ID1" picture="pic1.png">
        <name>AMD A4-5300 APU OEM</name>
        <delivery-date>2021-10-03</delivery-date>
        <country>Canada</country>
        <price>65.24</price>
        <property>
            <peripheral>in case</peripheral>
            <port>FM2</port>
        </property>
        <critical>true</critical>
        <frequency>5300</frequency>
    </cpu>

    <hdd id="ID9" picture="pic9.png">
        <name>Seagate Exos X16</name>
        <delivery-date>2020-03-01</delivery-date>
        <country>USA</country>
        <price>78.45</price>
        <property>
            <peripheral>in case</peripheral>
            <port>SATA</port>
        </property>
        <critical>true</critical>
        <volume>16</volume>
    </hdd>

</devices>

=== Petrovich-A/EPAM-Task-Xml-Parsing/src/main/resources/files/computers.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/computers"
         xsi:schemaLocation="http://www.example.com/computers computers.xsd">

    <cpu id="ID1" picture="fir.png">
        <name>ASRock</name>
        <delivery-date>2021-10-03</delivery-date>
        <country>Canada</country>
        <price>65.24</price>
        <atribute>
            <peripheral>in case</peripheral>
            <port>SATA</port>
        </atribute>
        <critical>true</critical>
        <sequanse>1800</sequanse>
    </cpu>
    <hdd id="ID2" picture="fir.png">
        <name>AMD</name>
        <delivery-date>2021-01-08</delivery-date>
        <country>USA</country>
        <price>65.24</price>
        <atribute>
            <peripheral>in case</peripheral>
            <port>SATA</port>
        </atribute>
        <critical>true</critical>
        <volume>1800</volume>
    </hdd>
</devices>
